site_name: Plus Mobile Apps
site_description: Mobile apps company and tech blog
site_url: https://plusmobileapps.com

theme:
  name: material
  logo: assets/plus-logo.jpeg
  favicon: assets/plus-logo.jpeg
  features: 
    - navigation.footer
    - navigation.tabs
    - content.code.copy
  custom_dir: overrides
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - blog
  - redirects:
      redirect_maps:
        '2024/05/25/flyway-exposed-ktor.html' : 'blog/posts/2024-05-25-flyway-exposed-ktor.md'
        '2022/08/02/ktor-firebase-auth.html' : 'blog/posts/2022-08-02-ktor-firebase-auth.md'
        '2022/05/04/lazy-column-view-impressions.html' : 'blog/posts/2022-05-04-lazy-column-view-impressions.md'
        '2022/01/06/save-state-flow.html' : 'blog/posts/2022-01-06-save-state-flow.md'
        '2020/12/14/android-custom-view-testing.html' : 'blog/posts/2020-12-14-android-custom-view-testing.md'
        '2020/10/09/ktor-slackbot-heroku.html' : 'blog/posts/2020-10-09-ktor-slackbot-heroku.md'
        '2020/05/06/create-gh-pages-site.html' : 'blog/posts/2020-05-06-create-gh-pages-site.md'
        '2020/03/02/physical-workspace.html' : 'blog/posts/2020-03-02-physical-workspace.md'
        '2020/01/26/mac-dev-environment.html' : 'blog/posts/2020-01-26-mac-dev-environment.md'
        '2020/01/20/markdown.html' : 'blog/posts/2020-01-20-markdown.md'
        '2019/08/14/kotlin-or-java.html' : 'blog/posts/2019-08-14-kotlin-or-java.md'
        '2019/05/26/analysis-paralysis.html' : 'blog/posts/2019-05-26-analysis-paralysis.md'
        '2019/03/05/android-terminal-tricks.html' : 'blog/posts/2019-03-05-android-terminal-tricks.md'
        '2018/09/26/android-location-basics.html' : 'blog/posts/2018-09-26-android-location-basics.md'
        '2018/07/30/shell-scripts.html' : 'blog/posts/2018-07-30-shell-scripts.md'
        '2018/07/20/ssh.html' : 'blog/posts/2018-07-20-ssh.md'

extra:
  analytics:
    provider: google
    property: G-FDVQ64BD8G
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/plusmobileapps
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/plusmobileapps
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/andrew-steinmetz-6a8aaaa2/

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Blog: 
    - blog/index.md
  - About:
    - about.md